// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppState is returned by GetState.
 */
export class AppState {
    /**
     * Creates a new AppState instance.
     * @param {Partial<AppState>} [$$source = {}] - The source object to create the AppState.
     */
    constructor($$source = {}) {
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rootPath"] = undefined;
        }
        if (!("hasData" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasData"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["selected"] = undefined;
        }
        if (!("scanning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["scanning"] = false;
        }
        if (!("groupCount" in $$source)) {
            /**
             * Similarity group picker (phase 4): GroupIndex is -1 until a group is chosen when GroupCount > 1.
             * @member
             * @type {number}
             */
            this["groupCount"] = 0;
        }
        if (!("groupIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["groupIndex"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["groupLabels"] = undefined;
        }
        if (!("needGroupPick" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needGroupPick"] = false;
        }
        if (!("compareRowCount" in $$source)) {
            /**
             * RowCount is len(folder rows)+len(file rows) in the compare table when a merge is active.
             * @member
             * @type {number}
             */
            this["compareRowCount"] = 0;
        }
        if (!("applyRunning" in $$source)) {
            /**
             * ApplyRunning is true while the on-disk executor is working (phase 5).
             * @member
             * @type {boolean}
             */
            this["applyRunning"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppState}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groupLabels" in $$parsedSource) {
            $$parsedSource["groupLabels"] = $$createField8_0($$parsedSource["groupLabels"]);
        }
        return new AppState(/** @type {Partial<AppState>} */($$parsedSource));
    }
}

/**
 * DirEntry is a single filesystem entry used by ListDir (server-mode directory picker).
 */
export class DirEntry {
    /**
     * Creates a new DirEntry instance.
     * @param {Partial<DirEntry>} [$$source = {}] - The source object to create the DirEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DirEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DirEntry(/** @type {Partial<DirEntry>} */($$parsedSource));
    }
}

/**
 * FolderNode is a JSON tree node for the folder view.
 */
export class FolderNode {
    /**
     * Creates a new FolderNode instance.
     * @param {Partial<FolderNode>} [$$source = {}] - The source object to create the FolderNode.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("totalSizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSizeBytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FolderNode[] | undefined}
             */
            this["children"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FolderNode}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField3_0($$parsedSource["children"]);
        }
        return new FolderNode(/** @type {Partial<FolderNode>} */($$parsedSource));
    }
}

/**
 * MergeFileRow is one row in the compare table (files and subfolder rows).
 */
export class MergeFileRow {
    /**
     * Creates a new MergeFileRow instance.
     * @param {Partial<MergeFileRow>} [$$source = {}] - The source object to create the MergeFileRow.
     */
    constructor($$source = {}) {
        if (!("rowIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rowIndex"] = 0;
        }
        if (!("isFolder" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isFolder"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["no"] = undefined;
        }
        if (!("action" in $$source)) {
            /**
             * Action is none|deleteRight|deleteLeft|moveToRight|moveToLeft (matches core merge actions).
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["leftName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rightName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["leftPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rightPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["leftMeta"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rightMeta"] = undefined;
        }
        if (!("kind" in $$source)) {
            /**
             * "folder", "pair", "left", "right"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("similarityPct" in $$source)) {
            /**
             * SimilarityPct is 100 for exact hash match, -1 for similar pair (different hash), 0 for unique.
             * @member
             * @type {number}
             */
            this["similarityPct"] = 0;
        }
        if (!("leftSizeBytes" in $$source)) {
            /**
             * LeftSizeBytes / RightSizeBytes are file sizes for merge pair rows (0 when file absent on that side).
             * @member
             * @type {number}
             */
            this["leftSizeBytes"] = 0;
        }
        if (!("rightSizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rightSizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeFileRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeFileRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeFileRow(/** @type {Partial<MergeFileRow>} */($$parsedSource));
    }
}

/**
 * MergePreview is a read-only view of a folder pair and file rows.
 */
export class MergePreview {
    /**
     * Creates a new MergePreview instance.
     * @param {Partial<MergePreview>} [$$source = {}] - The source object to create the MergePreview.
     */
    constructor($$source = {}) {
        if (!("leftPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["leftPath"] = "";
        }
        if (!("rightPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rightPath"] = "";
        }
        if (!("leftLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["leftLabel"] = "";
        }
        if (!("rightLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rightLabel"] = "";
        }
        if (!("leftDupPct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["leftDupPct"] = 0;
        }
        if (!("rightDupPct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rightDupPct"] = 0;
        }
        if (!("leftTotalFiles" in $$source)) {
            /**
             * LeftTotalFiles / RightTotalFiles count files directly in the compared folder only.
             * @member
             * @type {number}
             */
            this["leftTotalFiles"] = 0;
        }
        if (!("rightTotalFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rightTotalFiles"] = 0;
        }
        if (!("leftTotalFilesRecursive" in $$source)) {
            /**
             * LeftTotalFilesRecursive / RightTotalFilesRecursive include all files under subfolders.
             * @member
             * @type {number}
             */
            this["leftTotalFilesRecursive"] = 0;
        }
        if (!("rightTotalFilesRecursive" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rightTotalFilesRecursive"] = 0;
        }
        if (!("leftChildFilesSizeBytes" in $$source)) {
            /**
             * ChildFilesSize = sum of sizes of files directly in the folder (same scope as LeftTotalFiles).
             * @member
             * @type {number}
             */
            this["leftChildFilesSizeBytes"] = 0;
        }
        if (!("rightChildFilesSizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rightChildFilesSizeBytes"] = 0;
        }
        if (!("leftTotalFilesSizeBytes" in $$source)) {
            /**
             * TotalFilesSize = sum of sizes of all files under the folder tree (same scope as recursive file counts).
             * @member
             * @type {number}
             */
            this["leftTotalFilesSizeBytes"] = 0;
        }
        if (!("rightTotalFilesSizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rightTotalFilesSizeBytes"] = 0;
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {MergeFileRow[]}
             */
            this["rows"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["note"] = undefined;
        }
        if (!("groupCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["groupCount"] = 0;
        }
        if (!("shownGroupIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["shownGroupIndex"] = 0;
        }
        if (!("interactive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["interactive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergePreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergePreview}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField14_0($$parsedSource["rows"]);
        }
        return new MergePreview(/** @type {Partial<MergePreview>} */($$parsedSource));
    }
}

/**
 * PhaseEvent is emitted when scan/load state changes.
 */
export class PhaseEvent {
    /**
     * Creates a new PhaseEvent instance.
     * @param {Partial<PhaseEvent>} [$$source = {}] - The source object to create the PhaseEvent.
     */
    constructor($$source = {}) {
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PhaseEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PhaseEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PhaseEvent(/** @type {Partial<PhaseEvent>} */($$parsedSource));
    }
}

/**
 * ProgressEvent is emitted during ApplyExecute (phase 5).
 */
export class ProgressEvent {
    /**
     * Creates a new ProgressEvent instance.
     * @param {Partial<ProgressEvent>} [$$source = {}] - The source object to create the ProgressEvent.
     */
    constructor($$source = {}) {
        if (!("phase" in $$source)) {
            /**
             * "running", "done", "cancelled", "error"
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["current"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["total"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgressEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProgressEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgressEvent(/** @type {Partial<ProgressEvent>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = FolderNode.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = MergeFileRow.createFrom;
const $$createType4 = $Create.Array($$createType3);
