// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppState is returned by GetState.
 */
export class AppState {
    "phase": string;
    "message"?: string;
    "rootPath"?: string;
    "hasData": boolean;
    "selected"?: string;
    "scanning": boolean;

    /**
     * Similarity group picker (phase 4): GroupIndex is -1 until a group is chosen when GroupCount > 1.
     */
    "groupCount": number;
    "groupIndex": number;
    "groupLabels"?: string[];
    "needGroupPick": boolean;

    /**
     * RowCount is len(folder rows)+len(file rows) in the compare table when a merge is active.
     */
    "compareRowCount": number;

    /**
     * ApplyRunning is true while the on-disk executor is working (phase 5).
     */
    "applyRunning": boolean;

    /** Creates a new AppState instance. */
    constructor($$source: Partial<AppState> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("hasData" in $$source)) {
            this["hasData"] = false;
        }
        if (!("scanning" in $$source)) {
            this["scanning"] = false;
        }
        if (!("groupCount" in $$source)) {
            this["groupCount"] = 0;
        }
        if (!("groupIndex" in $$source)) {
            this["groupIndex"] = 0;
        }
        if (!("needGroupPick" in $$source)) {
            this["needGroupPick"] = false;
        }
        if (!("compareRowCount" in $$source)) {
            this["compareRowCount"] = 0;
        }
        if (!("applyRunning" in $$source)) {
            this["applyRunning"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppState instance from a string or object.
     */
    static createFrom($$source: any = {}): AppState {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groupLabels" in $$parsedSource) {
            $$parsedSource["groupLabels"] = $$createField8_0($$parsedSource["groupLabels"]);
        }
        return new AppState($$parsedSource as Partial<AppState>);
    }
}

/**
 * FolderNode is a JSON tree node for the folder view.
 */
export class FolderNode {
    "path": string;
    "name": string;
    "totalSizeBytes": number;
    "children"?: FolderNode[];

    /** Creates a new FolderNode instance. */
    constructor($$source: Partial<FolderNode> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("totalSizeBytes" in $$source)) {
            this["totalSizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderNode instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderNode {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField3_0($$parsedSource["children"]);
        }
        return new FolderNode($$parsedSource as Partial<FolderNode>);
    }
}

/**
 * MergeFileRow is one row in the compare table (files and subfolder rows).
 */
export class MergeFileRow {
    "rowIndex": number;
    "isFolder": boolean;
    "no"?: string;

    /**
     * Action is none|deleteRight|deleteLeft|moveToRight|moveToLeft (matches core merge actions).
     */
    "action": string;
    "leftName"?: string;
    "rightName"?: string;
    "leftPath"?: string;
    "rightPath"?: string;
    "leftMeta"?: string;
    "rightMeta"?: string;

    /**
     * "folder", "pair", "left", "right"
     */
    "kind": string;

    /**
     * SimilarityPct is 100 for exact hash match, -1 for similar pair (different hash), 0 for unique.
     */
    "similarityPct": number;

    /**
     * LeftSizeBytes / RightSizeBytes are file sizes for merge pair rows (0 when file absent on that side).
     */
    "leftSizeBytes": number;
    "rightSizeBytes": number;

    /** Creates a new MergeFileRow instance. */
    constructor($$source: Partial<MergeFileRow> = {}) {
        if (!("rowIndex" in $$source)) {
            this["rowIndex"] = 0;
        }
        if (!("isFolder" in $$source)) {
            this["isFolder"] = false;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("similarityPct" in $$source)) {
            this["similarityPct"] = 0;
        }
        if (!("leftSizeBytes" in $$source)) {
            this["leftSizeBytes"] = 0;
        }
        if (!("rightSizeBytes" in $$source)) {
            this["rightSizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeFileRow instance from a string or object.
     */
    static createFrom($$source: any = {}): MergeFileRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeFileRow($$parsedSource as Partial<MergeFileRow>);
    }
}

/**
 * MergePreview is a read-only view of a folder pair and file rows.
 */
export class MergePreview {
    "leftPath": string;
    "rightPath": string;
    "leftLabel": string;
    "rightLabel": string;
    "leftDupPct": number;
    "rightDupPct": number;

    /**
     * LeftTotalFiles / RightTotalFiles count files directly in the compared folder only.
     */
    "leftTotalFiles": number;
    "rightTotalFiles": number;

    /**
     * LeftTotalFilesRecursive / RightTotalFilesRecursive include all files under subfolders.
     */
    "leftTotalFilesRecursive": number;
    "rightTotalFilesRecursive": number;

    /**
     * ChildFilesSize = sum of sizes of files directly in the folder (same scope as LeftTotalFiles).
     */
    "leftChildFilesSizeBytes": number;
    "rightChildFilesSizeBytes": number;

    /**
     * TotalFilesSize = sum of sizes of all files under the folder tree (same scope as recursive file counts).
     */
    "leftTotalFilesSizeBytes": number;
    "rightTotalFilesSizeBytes": number;
    "rows": MergeFileRow[];
    "note"?: string;
    "groupCount": number;
    "shownGroupIndex": number;
    "interactive": boolean;

    /** Creates a new MergePreview instance. */
    constructor($$source: Partial<MergePreview> = {}) {
        if (!("leftPath" in $$source)) {
            this["leftPath"] = "";
        }
        if (!("rightPath" in $$source)) {
            this["rightPath"] = "";
        }
        if (!("leftLabel" in $$source)) {
            this["leftLabel"] = "";
        }
        if (!("rightLabel" in $$source)) {
            this["rightLabel"] = "";
        }
        if (!("leftDupPct" in $$source)) {
            this["leftDupPct"] = 0;
        }
        if (!("rightDupPct" in $$source)) {
            this["rightDupPct"] = 0;
        }
        if (!("leftTotalFiles" in $$source)) {
            this["leftTotalFiles"] = 0;
        }
        if (!("rightTotalFiles" in $$source)) {
            this["rightTotalFiles"] = 0;
        }
        if (!("leftTotalFilesRecursive" in $$source)) {
            this["leftTotalFilesRecursive"] = 0;
        }
        if (!("rightTotalFilesRecursive" in $$source)) {
            this["rightTotalFilesRecursive"] = 0;
        }
        if (!("leftChildFilesSizeBytes" in $$source)) {
            this["leftChildFilesSizeBytes"] = 0;
        }
        if (!("rightChildFilesSizeBytes" in $$source)) {
            this["rightChildFilesSizeBytes"] = 0;
        }
        if (!("leftTotalFilesSizeBytes" in $$source)) {
            this["leftTotalFilesSizeBytes"] = 0;
        }
        if (!("rightTotalFilesSizeBytes" in $$source)) {
            this["rightTotalFilesSizeBytes"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("groupCount" in $$source)) {
            this["groupCount"] = 0;
        }
        if (!("shownGroupIndex" in $$source)) {
            this["shownGroupIndex"] = 0;
        }
        if (!("interactive" in $$source)) {
            this["interactive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergePreview instance from a string or object.
     */
    static createFrom($$source: any = {}): MergePreview {
        const $$createField14_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField14_0($$parsedSource["rows"]);
        }
        return new MergePreview($$parsedSource as Partial<MergePreview>);
    }
}

/**
 * PhaseEvent is emitted when scan/load state changes.
 */
export class PhaseEvent {
    "phase": string;
    "message"?: string;

    /** Creates a new PhaseEvent instance. */
    constructor($$source: Partial<PhaseEvent> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PhaseEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): PhaseEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PhaseEvent($$parsedSource as Partial<PhaseEvent>);
    }
}

/**
 * ProgressEvent is emitted during ApplyExecute (phase 5).
 */
export class ProgressEvent {
    /**
     * "running", "done", "cancelled", "error"
     */
    "phase": string;
    "current"?: number;
    "total"?: number;
    "message"?: string;
    "error"?: string;

    /** Creates a new ProgressEvent instance. */
    constructor($$source: Partial<ProgressEvent> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgressEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ProgressEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgressEvent($$parsedSource as Partial<ProgressEvent>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = FolderNode.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = MergeFileRow.createFrom;
const $$createType4 = $Create.Array($$createType3);
