//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../../../../folder-similarity/app/dto/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "phase": $$createType0,
        "progress": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = dto$0.PhaseEvent.createFrom;
const $$createType1 = dto$0.ProgressEvent.createFrom;

configure();
