// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Similarity is the Wails service backing the tree/compare UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../dto/models.js";

/**
 * ApplyExecute runs the on-disk executor for the current merge. Errors during execution are sent on the "progress" event; this returns only validation / start-up errors.
 * @returns {$CancellablePromise<void>}
 */
export function ApplyExecute() {
    return $Call.ByID(604229685);
}

/**
 * CancelApply requests cancellation of a running apply (same as TUI cancel during executor).
 * @returns {$CancellablePromise<void>}
 */
export function CancelApply() {
    return $Call.ByID(2712270200);
}

/**
 * CancelScan aborts a running directory scan.
 * @returns {$CancellablePromise<void>}
 */
export function CancelScan() {
    return $Call.ByID(3783794789);
}

/**
 * ClearAllCompareRowActions sets every row to none.
 * @returns {$CancellablePromise<void>}
 */
export function ClearAllCompareRowActions() {
    return $Call.ByID(173001250);
}

/**
 * ClearCompareRowAction clears a single row (same as action "none").
 * @param {number} rowIndex
 * @returns {$CancellablePromise<void>}
 */
export function ClearCompareRowAction(rowIndex) {
    return $Call.ByID(2364443088, rowIndex);
}

/**
 * ExportDataToJSON writes the current in-memory file list to a path chosen in a save dialog (phase 6; same data shape as the TUI’s ExportStorage / db.json).
 * @returns {$CancellablePromise<void>}
 */
export function ExportDataToJSON() {
    return $Call.ByID(4038478851);
}

/**
 * GetApplyPreview returns human-readable action lines (phase 4 dry run; does not execute).
 * @returns {$CancellablePromise<string[]>}
 */
export function GetApplyPreview() {
    return $Call.ByID(2454762622).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetApplySummary returns a user-facing confirmation string (TUI-style counts) plus root.
 * @returns {$CancellablePromise<string>}
 */
export function GetApplySummary() {
    return $Call.ByID(423274478);
}

/**
 * GetExportedJSON returns the current in-memory file list as a JSON string.
 * Used by server-mode frontend to trigger a browser download (Blob + <a download>).
 * @returns {$CancellablePromise<string>}
 */
export function GetExportedJSON() {
    return $Call.ByID(1855248727);
}

/**
 * GetMergePreview returns the compare view including per-row action state.
 * @returns {$CancellablePromise<dto$0.MergePreview>}
 */
export function GetMergePreview() {
    return $Call.ByID(2243443726).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetState returns a snapshot of lifecycle, selection, and group-picker state.
 * @returns {$CancellablePromise<dto$0.AppState>}
 */
export function GetState() {
    return $Call.ByID(1976794911).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetTree returns the folder tree, optionally pruned to folders that participate in similarity.
 * @param {boolean} similarityOnly
 * @returns {$CancellablePromise<dto$0.FolderNode>}
 */
export function GetTree(similarityOnly) {
    return $Call.ByID(2877660742, similarityOnly).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * HomeDir returns the current user's home directory. Used by the server-mode folder picker
 * to seed its initial location.
 * @returns {$CancellablePromise<string>}
 */
export function HomeDir() {
    return $Call.ByID(3059876288);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsServerMode() {
    return $Call.ByID(3258915730);
}

/**
 * ListDir lists immediate child directories of path. If filterExt is non-empty (e.g. ".json"),
 * matching files are included as well. Used by the server-mode folder/file picker.
 * path must be absolute.
 * @param {string} path
 * @param {string} filterExt
 * @returns {$CancellablePromise<dto$0.DirEntry[]>}
 */
export function ListDir(path, filterExt) {
    return $Call.ByID(3365801681, path, filterExt).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * LoadFromJSONFile loads a previously exported file list.
 * @param {string} abs
 * @returns {$CancellablePromise<void>}
 */
export function LoadFromJSONFile(abs) {
    return $Call.ByID(3082201554, abs);
}

/**
 * OpenScannedPath opens a scan-root-relative path (matches core File/Folder.Path) using the OS default handler.
 * @param {string} relPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenScannedPath(relPath) {
    return $Call.ByID(2490153141, relPath);
}

/**
 * PickJSONFile opens a file picker for JSON (saved db).
 * @returns {$CancellablePromise<string>}
 */
export function PickJSONFile() {
    return $Call.ByID(1538654363);
}

/**
 * PickRootFolder opens a directory picker. Returns the absolute path or an empty string if cancelled.
 * @returns {$CancellablePromise<string>}
 */
export function PickRootFolder() {
    return $Call.ByID(612538823);
}

/**
 * ReadGalleryImagePreview reads an image file under the current scan root and returns a data URL
 * for display in the webview (raw file:// URLs are often blocked by embedded browsers).
 * 
 * HEIF (.heic / .heif) are transcoded with go-astiav where CGO + FFmpeg/heif codecs are present.
 * 
 * Supported video extensions return a synthesized JPEG thumbnail (first frame ~1s, downscaled via go-astiav).
 * @param {string} relPath
 * @returns {$CancellablePromise<string>}
 */
export function ReadGalleryImagePreview(relPath) {
    return $Call.ByID(132128711, relPath);
}

/**
 * RevealMergeFolder opens the system file manager for the left or right folder of the active merge (phase 6; TUI: OpenFileExplorer). side is "left" or "right".
 * @param {string} side
 * @returns {$CancellablePromise<void>}
 */
export function RevealMergeFolder(side) {
    return $Call.ByID(2482739505, side);
}

/**
 * RevealScannedPath opens the OS file manager for the path; for files, selects the file in its parent folder on macOS and Windows.
 * @param {string} relPath
 * @returns {$CancellablePromise<void>}
 */
export function RevealScannedPath(relPath) {
    return $Call.ByID(1842248582, relPath);
}

/**
 * SelectFolder sets the selected folder and either builds the merge (one group) or opens group selection (many).
 * @param {string} rel
 * @returns {$CancellablePromise<void>}
 */
export function SelectFolder(rel) {
    return $Call.ByID(105740182, rel);
}

/**
 * SelectSimilarityGroupIndex applies when multiple groups exist; index is 0-based.
 * @param {number} i
 * @returns {$CancellablePromise<void>}
 */
export function SelectSimilarityGroupIndex(i) {
    return $Call.ByID(467079352, i);
}

/**
 * SetAllCompareRowActions sets the same action on every row.
 * @param {string} action
 * @returns {$CancellablePromise<void>}
 */
export function SetAllCompareRowActions(action) {
    return $Call.ByID(1078384091, action);
}

/**
 * SetCompareRowAction sets the merge action for a row (folder rows first, then file rows, 0-based).
 * @param {number} rowIndex
 * @param {string} action
 * @returns {$CancellablePromise<void>}
 */
export function SetCompareRowAction(rowIndex, action) {
    return $Call.ByID(2681793377, rowIndex, action);
}

/**
 * StartScan sets root to an absolute path and scans asynchronously.
 * @param {string} rootAbs
 * @returns {$CancellablePromise<void>}
 */
export function StartScan(rootAbs) {
    return $Call.ByID(473766299, rootAbs);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = dto$0.MergePreview.createFrom;
const $$createType2 = dto$0.AppState.createFrom;
const $$createType3 = dto$0.FolderNode.createFrom;
const $$createType4 = dto$0.DirEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
