// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Similarity is the Wails service backing the tree/compare UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../dto/models.js";

/**
 * ApplyExecute runs the on-disk executor for the current merge. Errors during execution are sent on the "progress" event; this returns only validation / start-up errors.
 */
export function ApplyExecute(): $CancellablePromise<void> {
    return $Call.ByID(604229685);
}

/**
 * CancelApply requests cancellation of a running apply (same as TUI cancel during executor).
 */
export function CancelApply(): $CancellablePromise<void> {
    return $Call.ByID(2712270200);
}

/**
 * CancelScan aborts a running directory scan.
 */
export function CancelScan(): $CancellablePromise<void> {
    return $Call.ByID(3783794789);
}

/**
 * ClearAllCompareRowActions sets every row to none.
 */
export function ClearAllCompareRowActions(): $CancellablePromise<void> {
    return $Call.ByID(173001250);
}

/**
 * ClearCompareRowAction clears a single row (same as action "none").
 */
export function ClearCompareRowAction(rowIndex: number): $CancellablePromise<void> {
    return $Call.ByID(2364443088, rowIndex);
}

/**
 * ExportDataToJSON writes the current in-memory file list to a path chosen in a save dialog (phase 6; same data shape as the TUI’s ExportStorage / db.json).
 */
export function ExportDataToJSON(): $CancellablePromise<void> {
    return $Call.ByID(4038478851);
}

/**
 * GetApplyPreview returns human-readable action lines (phase 4 dry run; does not execute).
 */
export function GetApplyPreview(): $CancellablePromise<string[]> {
    return $Call.ByID(2454762622).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetApplySummary returns a user-facing confirmation string (TUI-style counts) plus root.
 */
export function GetApplySummary(): $CancellablePromise<string> {
    return $Call.ByID(423274478);
}

/**
 * GetMergePreview returns the compare view including per-row action state.
 */
export function GetMergePreview(): $CancellablePromise<dto$0.MergePreview> {
    return $Call.ByID(2243443726).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetState returns a snapshot of lifecycle, selection, and group-picker state.
 */
export function GetState(): $CancellablePromise<dto$0.AppState> {
    return $Call.ByID(1976794911).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetTree returns the folder tree, optionally pruned to folders that participate in similarity.
 */
export function GetTree(similarityOnly: boolean): $CancellablePromise<dto$0.FolderNode> {
    return $Call.ByID(2877660742, similarityOnly).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * LoadFromJSONFile loads a previously exported file list.
 */
export function LoadFromJSONFile(abs: string): $CancellablePromise<void> {
    return $Call.ByID(3082201554, abs);
}

/**
 * OpenScannedPath opens a scan-root-relative path (matches core File/Folder.Path) using the OS default handler.
 */
export function OpenScannedPath(relPath: string): $CancellablePromise<void> {
    return $Call.ByID(2490153141, relPath);
}

/**
 * PickJSONFile opens a file picker for JSON (saved db).
 */
export function PickJSONFile(): $CancellablePromise<string> {
    return $Call.ByID(1538654363);
}

/**
 * PickRootFolder opens a directory picker. Returns the absolute path or an empty string if cancelled.
 */
export function PickRootFolder(): $CancellablePromise<string> {
    return $Call.ByID(612538823);
}

/**
 * ReadGalleryImagePreview reads an image file under the current scan root and returns a data URL
 * for display in the webview (raw file:// URLs are often blocked by embedded browsers).
 * 
 * HEIF (.heic / .heif) are transcoded with go-astiav where CGO + FFmpeg/heif codecs are present.
 * 
 * Supported video extensions return a synthesized JPEG thumbnail (first frame ~1s, downscaled via go-astiav).
 */
export function ReadGalleryImagePreview(relPath: string): $CancellablePromise<string> {
    return $Call.ByID(132128711, relPath);
}

/**
 * RevealMergeFolder opens the system file manager for the left or right folder of the active merge (phase 6; TUI: OpenFileExplorer). side is "left" or "right".
 */
export function RevealMergeFolder(side: string): $CancellablePromise<void> {
    return $Call.ByID(2482739505, side);
}

/**
 * RevealScannedPath opens the OS file manager for the path; for files, selects the file in its parent folder on macOS and Windows.
 */
export function RevealScannedPath(relPath: string): $CancellablePromise<void> {
    return $Call.ByID(1842248582, relPath);
}

/**
 * SelectFolder sets the selected folder and either builds the merge (one group) or opens group selection (many).
 */
export function SelectFolder(rel: string): $CancellablePromise<void> {
    return $Call.ByID(105740182, rel);
}

/**
 * SelectSimilarityGroupIndex applies when multiple groups exist; index is 0-based.
 */
export function SelectSimilarityGroupIndex(i: number): $CancellablePromise<void> {
    return $Call.ByID(467079352, i);
}

/**
 * SetAllCompareRowActions sets the same action on every row.
 */
export function SetAllCompareRowActions(action: string): $CancellablePromise<void> {
    return $Call.ByID(1078384091, action);
}

/**
 * SetCompareRowAction sets the merge action for a row (folder rows first, then file rows, 0-based).
 */
export function SetCompareRowAction(rowIndex: number, action: string): $CancellablePromise<void> {
    return $Call.ByID(2681793377, rowIndex, action);
}

/**
 * StartScan sets root to an absolute path and scans asynchronously.
 */
export function StartScan(rootAbs: string): $CancellablePromise<void> {
    return $Call.ByID(473766299, rootAbs);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = dto$0.MergePreview.createFrom;
const $$createType2 = dto$0.AppState.createFrom;
const $$createType3 = dto$0.FolderNode.createFrom;
